language: ruby
dependencies:
  cache_directories:
    - public/assets
    - tmp/cache/assets
deploy:
  provider: heroku
  api_key:
    secure: kDHyp44GIPT9sGSQD3mOS+rrbSx2xHKYrQUXJ1cfZLpYgA8Dj1BrgZJy75wBaep4YTCdoAcddgKMNAVB6IRe5Re7QVprJWObYqUXzDL+YhoG0RfYXB412yHNvYYJC1hZCfwrfxhMLm8gHkFt9JkiBlxFfiei+2wta9b499oK1E/wdBe7cmTbcSnXRHKnHM6UwVD6LA83jB6/HdowfVYFVksx/e3JpFqJgLwYhF3UqDwXaBl7NNhl57mZUU7WDFqwxS6YZMGRjvmIOS1UrNZV8mliG3CZJ+FnJ8B3coUtnJoVgPJGyxMLHy1hyN0+NzJiG8RZ/lNjFlTHV5C2AlfZ/EgpNZew0f86EwZUf7YjkrtZmWJOhLFrjE23RLDawIJZB2tNN5Snn7wR+xOCNsQ/JDnw/cmvkuKmCKPvwRPLpwt51bm8pecH37cr95e5drbNWz05CPLHhzb4WKstpjGORvrUnj1VVKaVZFfpsqvj6ah/bDWjLk2XLm9G5fXuKrYUr471sVfW/Nlig/rfTfSdwEVnzkV/ejPPzHuoausnVMqfoU4qCNH4v6qaEqkJaQYOAQgZqviRoFoJzLAue3ZYSx+jPMBqSXjkb6zLKkS+sRNM9mLz65T29QxtkwxKMK1JHOBQq4Tr1NjBaSjIYsA52fW0hKmRH4uo7oQxrA4i8W4=
  app:
    master: coderdojo-japan
  run:
    - bundle exec rails db:migrate
    - bundle exec rails db:seed
    - bundle exec rails dojos:update_db_by_yaml
    - bundle exec rails dojo_event_services:upsert
cache:
  - bundler
# TODO:before_installは次のissueが解決したら削除
# cf. https://github.com/travis-ci/travis-ci/issues/9333#issuecomment-373042916
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database coderdojo_jp_test;' -U postgres
script:
  - bundle exec rake db:migrate --trace
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec rspec spec; fi
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_PULL_REQUEST_SLUG" = "coderdojo-japan/coderdojo.jp" ]; then bundle exec rspec spec; fi
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_PULL_REQUEST_SLUG" != "coderdojo-japan/coderdojo.jp" ]; then bundle exec rspec spec --tag ~@scrivito; fi
env:
  global:
    - TZ='Asia/Tokyo'
addons:
  postgresql: '9.4'
